config/routes.rb
Rails.application.routes.draw do
	root 'home#top'
	get 'home/about'
	get 'home/howto'

	devise_for :admins, controllers: {
		sessions: 'admins/sessions',
		passwords:     'admins/passwords',
		registrations: 'admins/registrations'
	}

	devise_for :users, controllers: {
		sessions:      'users/sessions',
		passwords:     'users/passwords',
		registrations: 'users/registrations'
	}

	resources :users, only: [:show, :edit, :update] do
		member do
			get 'confirm'
		end
	end
	resources :diaries, only: [:index, :create, :update, :destroy] do
		member do
			get 'data'
		end
		collection do
			get 'record'
		end
	end
	resources :categories, only: [:index, :show]
	resources :inquiries, only: [:new, :create]

	namespace :admins do
		get 'home/top'
		resources :users, only: [:index]
		resources :foods, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :diaries, only: [:index, :show, :edit, :update, :destroy]
		resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :inquiries, only: [:index, :show, :destroy]
	end
end

app/models/food.rb
class Food < ApplicationRecord
	belongs_to :category
	validates :name, :caption, :category_id,  presence: true
end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < Admin::BaseController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.fetch(:food, {})
    end
end

app/controllers/admins/foods_controller.rb
class Admins::FoodsController < Admins::BaseController
  before_action :set_food, only: [:edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to admins_foods_path, notice: '食品を登録しました。' 
    else
      redirect_back(fallback_location: root_path, alert: @food.errors.full_messages.join(", "))
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    if @food.update(food_params)
      redirect_to admins_foods_path, notice: '食品の上書きが完了しました。' 
    else
      redirect_back(fallback_location: root_path, alert: @food.errors.full_messages.join(", "))
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    if @food.destroy
      redirect_to admins_foods_path, notice: '食品目を削除しました。' 
    else
      redirect_back(fallback_location: root_path, alert: @food.errors.full_messages.join(", "))
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :caption, :category_id)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.fetch(:food, {})
    end
end

app/helpers/admins/foods_helper.rb
module Admins::FoodsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/admins/foods/_form.html.slim
= form_for [:admins, @food] do |f|
	.form-group.mb-4
		= f.label :食品名, class: "font-weight-bold"
		= f.text_field :name, class: "form-control"
	.form-group.mb-4
		= f.label :カロリー目安, class: "font-weight-bold"
		= f.text_area :caption, class: "form-control"
	.form-group.mb-4
		= f.label :食品目, class: "font-weight-bold"
		= f.select :category_id, Category.all.map{|t|[t.name, t.id]}, {}, class: "form-control"
	.text-center.mb-4
		.actions = f.submit '登録', class: "btn page-link text-dark d-inline-block w-50"

app/views/admins/foods/edit.html.slim
.container.mb-4
	.row.mb-4
		.col-md-8.offset-md-2.my-auto
			h5.mt-4.mb-4 食品 編集
			== render 'form'
			.text-right
				=< link_to '戻る', admins_foods_path

app/views/admins/foods/index.html.slim
.container-fluid.mt-4
  .card.shadow.mb-4
    .card-header.py-3
      h6.m-0.font-weight-bold.text-primary
        | Foods
    .card-body
      .table-responsive
        table#dataTable.table.table-bordered[width="100%" cellspacing="0"]
          thead
            tr
              th
                | ID
              th
                | 食品名
              th
                | 品目名
              th
                | カロリー目安
              th
                |
              th
                |
          tbody
            - @foods.each do |food|
              tr
                td = food.id
                td = food.name
                td = food.category.name
                td = food.caption
                td = link_to '編集', edit_admins_food_path(food)
                td = link_to '削除', admins_food_path(food), data: { confirm: '本当に削除しますか？' }, method: :delete
  .row.mb-4
    .col-md-12.text-center
      = link_to '新規登録', new_admins_food_path, class: "btn page-link text-dark d-inline-block"

app/views/admins/foods/new.html.slim
.container.mb-4
	.row.mb-4
		.col-md-8.offset-md-2.my-auto
			h5.mt-4.mb-4 食品 登録
			== render 'form'
			.text-right
				=< link_to '戻る', admins_foods_path

app/views/admins/foods/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_admins_food_path(@food)
'|
=< link_to 'Back', admins_foods_path