config/routes.rb
Rails.application.routes.draw do
	root 'home#top'
	get 'home/about'
	get 'home/howto'

	devise_for :admins, controllers: {
		sessions: 'admins/sessions',
		passwords:     'admins/passwords',
		registrations: 'admins/registrations'
	}

	devise_for :users, controllers: {
		sessions:      'users/sessions',
		passwords:     'users/passwords',
		registrations: 'users/registrations'
	}

	resources :users, only: [:show, :edit, :update] do
		member do
			get 'confirm'
		end
	end
	resources :diaries, only: [:index, :create, :update, :destroy] do
		member do
			get 'data'
		end
		collection do
			get 'record'
		end
	end
	resources :categories, only: [:index, :show]
	resources :inquiries, only: [:new, :create]

	namespace :admins do
		get 'home/top'
		resources :users, only: [:index]
		resources :foods, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :diaries, only: [:index, :show, :edit, :update, :destroy]
		resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :inquiries, only: [:index, :show, :destroy]
	end
end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :user
	has_one :event
	has_many :diary_categories
	has_many :categories, through: :diary_categories
	has_one_attached :b_image
	has_one_attached :l_image
	has_one_attached :d_image

	validates :user_id, :status, presence: true
	validates :categories, presence: true
	enum status: {active:0, closed:1}
end

app/controllers/admin/diaries_controller.rb
class Admin::DiariesController < Admin::BaseController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.fetch(:diary, {})
    end
end

app/controllers/admins/diaries_controller.rb
class Admins::DiariesController < Admins::BaseController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/1/edit
  def edit
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to admins_diaries_path, notice: '上書きが完了しました。' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to admins_diaries_path, notice: '削除しました。' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:user_id, :b_image, :l_image, :d_image, :date, :weight, :comment, category_ids: [])
    end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_diary, only: [:show, :edit, :update, :destroy, :data]

	def index
		@diaries = current_user.diaries
		render 'index', formats: 'json', handlers: 'jbuilder'
	end

	def record
		@diary = current_user.diaries.find_or_initialize_by(date: params[:date])
		if @diary.new_record?
			render :new
		else
			render :edit
		end
	end


	# POST /diaries
	# POST /diaries.json
	def create
		@diary = current_user.diaries.new(diary_params)
		if @diary.save
			redirect_to current_user, notice: '登録が完了しました。'
		else
			redirect_back(fallback_location: root_path, alert: @diary.errors.full_messages.join(", "))
		end
	end

	# PATCH/PUT /diaries/1
	# PATCH/PUT /diaries/1.json
	def update
		if @diary.update(diary_params)
			redirect_to current_user, notice: '上書きが完了しました。' 
		else
			redirect_back(fallback_location: root_path, alert: @diary.errors.full_messages.join(", "))
		end
	end

	# DELETE /diaries/1
	# DELETE /diaries/1.json
	def destroy
		if @diary.destroy
			redirect_to current_user, notice: '削除しました。'
		else
			redirect_back(fallback_location: root_path, alert: @diary.errors.full_messages.join(", "))
		end
	end

	def data
		#選択した日から1週間前の摂取データを取得
		to  = @diary.date.at_end_of_day
		from = 6.days.ago(to).at_beginning_of_day
		#食品目ごとにデータを取得
		category_diaries_hash =
			current_user.diaries
				.where(date: from..to).map{|t|t.categories}
				.flatten.group_by(&:name)
				.map {|k, v| [k, v.size] }.to_h

		all_categories_hash = Category.all.map{ |c| [c.name, 0] }.to_h
		@records = all_categories_hash.merge(category_diaries_hash)
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_diary
			@diary = current_user.diaries.find(params[:id])
		end

		# Only allow a list of trusted parameters through.
		def diary_params
			params.require(:diary).permit(:user_id, :b_image, :l_image, :d_image, :date, :weight, :comment, category_ids: [])
		end
end

app/helpers/admins/diaries_helper.rb
module Admins::DiariesHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_form.html.slim
= form_with model: @diary, local: true do |f|
	= f.hidden_field :date, value: @diary.date
	.row.mb-4
		- Category.all.each do |c|
			.col-md-2.col-6.mb-4
				.card.img-thumbnail(style="height:100%")
					.card-img-top
						= image_tag c.image, width: "100%"
					.card-body
						.card-text.text-center.font-weight-bold
							= f.check_box :category_ids, {multiple: true}, c.id, nil
							= c.name
	.row.mb-4
		.col-md-4
			.form-group
				.File
					= f.label :朝ごはん, class: "font-weight-bold"
				.file.form-control-file
					= f.file_field :b_image
					- if @diary.b_image.attached?
      					= image_tag @diary.b_image, width: "100%", class: "p-2"
		.col-md-4
			.form-group
				.File
					= f.label :昼ごはん, class: "font-weight-bold"
				.file.form-control-file
					= f.file_field :l_image
					- if @diary.l_image.attached?
      					= image_tag @diary.l_image, width: "100%", class: "p-2"
		.col-md-4
			.form-group
				.File
					= f.label :晩ごはん, class: "font-weight-bold"
				.file.form-control-file
					= f.file_field :d_image
					- if @diary.d_image.attached?
      					= image_tag @diary.d_image, width: "100%", class: "p-2"
	
	.row.mb-4
		.col-md-4
			.form-group
				= f.label :体重, class: "font-weight-bold"
				= f.number_field :weight, min: 0, class: "form-control", placeholder: "体重を入力してください"
		.col-md-8
			.form-group
				= f.label :MEMO, class: "font-weight-bold"
				= f.text_area :comment, class: "form-control", placeholder: "今日のコメントを残しましょう", rows: 3
	.row.mt-4.p-md-2
		.col-md-12.text-center
			= f.submit '記録', class: "btn-flat-logo"

						

app/views/diaries/data.html.slim
.container
	.row
		.col-md-12.p-md-4
			h5.ml-2.font-weight-bold １週間のデータ
			h6　※毎日12品目全て摂取するのが理想的です
			h6.ml-4 グラフから不足している項目を確認しましょう

			canvas#mealChart height="200" width="400"

javascript:
	$(function () {
	    var ctx = document.getElementById('mealChart').getContext('2d');
	    var myChart = new Chart(ctx, {
	        type: 'bar',
	        data: {
	            labels: #{raw @records.map{|t| t[0]}},
	            datasets: [{
	                label: '摂取日数',
	                data: #{@records.map{|t| t[1]}},
	                backgroundColor: [
	                    'rgba(255, 99, 132, 0.2)',
	                    'rgba(255, 99, 132, 0.2)',
	                    'rgba(255, 99, 132, 0.2)',
	                    'rgba(255, 99, 132, 0.2)',
	                    'rgba(54, 162, 235, 0.2)',
	                    'rgba(54, 162, 235, 0.2)',
	                    'rgba(75, 192, 192, 0.2)',
	                    'rgba(255, 206, 86, 0.2)',
	                   	'rgba(255, 206, 86, 0.2)',
	                   	'rgba(255, 159, 64, 0.2)',
	                   	'rgba(255, 159, 64, 0.2)',
	                    'rgba(153, 102, 255, 0.2)'
	                ],
	                borderColor: [
	                    'rgba(255, 99, 132, 1)',
	                    'rgba(255, 99, 132, 1)',
	                    'rgba(255, 99, 132, 1)',
	                    'rgba(255, 99, 132, 1)',
	                    'rgba(54, 162, 235, 1)',
	                    'rgba(54, 162, 235, 1)',
	                    'rgba(75, 192, 192, 1)',
	                    'rgba(255, 206, 86, 1)',
	                    'rgba(255, 206, 86, 1)',
	                    'rgba(255, 159, 64, 1)',
	                    'rgba(255, 159, 64, 1)',
	                    'rgba(153, 102, 255, 1)'
	                ],
	                borderWidth: 1
	            }]
	        },
	        options: {
	            scales: {
	                yAxes: [{
	                    ticks: {
	                        beginAtZero: true,
	                        min: 0,
			                max: 7
	                    }
	                }]
	            }
	        }
	    });
	});

app/views/diaries/edit.html.slim
.container
	.row.mb-4
		.col-md-8
			p.font-weight-bold = @diary.date.strftime('%Y/%m/%d')
		.col-md-4
			= link_to '食品群・品目を調べる', categories_path, class: 'btn page-link text-dark mb-2'
			= link_to '１週間のデータを見る', data_diary_path(@diary), class: 'btn page-link text-dark'
	.row.mb-4
		.col-md-12
			== render 'form'
	.row.mb-4
		.col-md-12
			.text-right
				=> link_to '削除する', diary_path(@diary), method: :delete
				'｜
				=< link_to 'マイページへ', user_path(current_user)

app/views/diaries/new.html.slim
.container
	.row.mb-4
		.col-md-8
			p.font-weight-bold = @diary.date.strftime('%Y/%m/%d')
		.col-md-4
			.text-md-right
				= link_to '食品群・品目を調べる', categories_path, class: 'btn page-link text-dark'

	.row
		.col-md-12
			== render 'form'
		.col-md-12.mb-4
			.text-right
				= link_to '戻る', user_path(current_user)