config/routes.rb
Rails.application.routes.draw do
	root 'home#top'
	get 'home/about'
	get 'home/howto'

	devise_for :admins, controllers: {
		sessions: 'admins/sessions',
		passwords:     'admins/passwords',
		registrations: 'admins/registrations'
	}

	devise_for :users, controllers: {
		sessions:      'users/sessions',
		passwords:     'users/passwords',
		registrations: 'users/registrations'
	}

	resources :users, only: [:show, :edit, :update] do
		member do
			get 'confirm'
		end
	end
	resources :diaries, only: [:index, :create, :update, :destroy] do
		member do
			get 'data'
		end
		collection do
			get 'record'
		end
	end
	resources :categories, only: [:index, :show]
	resources :inquiries, only: [:new, :create]

	namespace :admins do
		get 'home/top'
		resources :users, only: [:index]
		resources :foods, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :diaries, only: [:index, :show, :edit, :update, :destroy]
		resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :inquiries, only: [:index, :show, :destroy]
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :foods
	has_many :diary_categories
	has_many :diaries, through: :diary_categories
	has_one_attached :image

	validates :name, :image, :nutrition_type, :food_group, :caption, presence: true

	enum nutrition_type: {body:0, arrange:1, energy:2}
	enum food_group: {first_group:0, second_group:1, third_group:2, fourth_group:3, fifth_group:4, sixth_group:5}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.fetch(:category, {})
    end
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < Admins::BaseController
	before_action :set_category, only: [:show, :edit, :update, :destroy]

	# GET /categories
	# GET /categories.json
	def index
		@categories = Category.all
	end

	# GET /categories/1
	# GET /categories/1.json
	def show
	end

	# GET /categories/new
	def new
		@category = Category.new
	end

	# GET /categories/1/edit
	def edit
	end

	# POST /categories
	# POST /categories.json
	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to admins_categories_path, notice: '食品目の作成が完了しました。' 
		else
			redirect_back(fallback_location: root_path, alert: @category.errors.full_messages.join(", "))
		end
	end

	# PATCH/PUT /categories/1
	# PATCH/PUT /categories/1.json
	def update
		if @category.update(category_params)
			redirect_to admins_categories_path, notice: '食品目の上書きが完了しました。' 
		else
			redirect_back(fallback_location: root_path, alert: @category.errors.full_messages.join(", "))
		end
	end

	# DELETE /categories/1
	# DELETE /categories/1.json
	def destroy
		if @category.destroy
			redirect_to admins_categories_path, notice: '食品目を削除しました。' 
		else
			redirect_back(fallback_location: root_path, alert: @category.errors.full_messages.join(", "))
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_category
			@category = Category.find(params[:id])
		end

		# Only allow a list of trusted parameters through.
		def category_params
			params.require(:category).permit(:image, :name, :nutrition_type, :food_group, :caption)
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show]

	# GET /categories
	# GET /categories.json
	def index
		@body_categories = Category.body
		@arange_categories = Category.arrange
		@energy_categories = Category.energy
	end

	# GET /categories/1
	# GET /categories/1.json
	def show
		@foods = @category.foods
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_category
			@category = Category.find(params[:id])
		end
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admins/categories/_form.html.slim
= form_for [:admins, @category] do |f|
	.form-group.mb-4
		.File
			= f.label :画像, class: "font-weight-bold"
		.file.form-control-file
			= f.file_field :image
			- if @category.image.attached? 
				= image_tag @category.image, width: "35%", class: "p-2"
	.form-group.mb-4
		= f.label :品目名, class: "font-weight-bold"
		= f.text_field :name, class: "form-control"
	.form-group.mb-4
		= f.label :説明, class: "font-weight-bold"
		= f.text_area :caption, class: "form-control"
	.form-group.mb-4
		= f.label :食品群, class: "font-weight-bold"
		= f.select :food_group, Category.food_groups_i18n.invert, {}, class: "form-control"
	.form-group.mb-4
		= f.label :栄養, class: "font-weight-bold"
		= f.select :nutrition_type, Category.nutrition_types_i18n.invert, {}, class: "form-control"
	.text-center.mb-4
		.actions = f.submit '登録', class: "btn page-link text-dark d-inline-block w-50"

app/views/admins/categories/edit.html.slim
.container.mb-4
	.row.mb-4
		.col-md-8.offset-md-2.my-auto
			h5.mt-4.mb-4 食品目 編集
			== render 'form'
			.text-right
				=< link_to '戻る', admins_categories_path

app/views/admins/categories/index.html.slim
.container-fluid.mt-4
  .card.shadow.mb-4
    .card-header.py-3
      h6.m-0.font-weight-bold.text-primary
        | Categories
    .card-body
      .table-responsive
        table#dataTable.table.table-bordered[width="100%" cellspacing="0"]
          thead
            tr
              th
                | 画像
              th
                | ID
              th
                | 品目名
              th
                | 食品群
              th
                | 栄養
              th
                |
              th
                |
          tbody
            - @categories.each do |category|
              tr
                td(style="width:100px")
                  = image_tag category.image, width: "100%"
                td = category.id
                td = category.name
                td = category.food_group_i18n
                td = category.nutrition_type_i18n
                td = link_to '編集', edit_admins_category_path(category)
                td = link_to '削除', admins_category_path(category), data: { confirm: '本当に削除しますか？' }, method: :delete

  .row.mb-4
    .col-md-12.text-center
      = link_to '新規登録', new_admins_category_path, class: "btn page-link text-dark d-inline-block"

app/views/admins/categories/new.html.slim
.container.mb-4
	.row.mb-4
		.col-md-8.offset-md-2.my-auto
			h5.mt-4.mb-4 食品目 登録
			== render 'form'
			.text-right
				=< link_to '戻る', admins_categories_path

app/views/admins/categories/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_category_path(@category)
'|
=< link_to 'Back', admins_categories_path