config/routes.rb
Rails.application.routes.draw do
	root 'home#top'
	get 'home/about'
	get 'home/howto'

	devise_for :admins, controllers: {
		sessions: 'admins/sessions',
		passwords:     'admins/passwords',
		registrations: 'admins/registrations'
	}

	devise_for :users, controllers: {
		sessions:      'users/sessions',
		passwords:     'users/passwords',
		registrations: 'users/registrations'
	}

	resources :users, only: [:show, :edit, :update] do
		member do
			get 'confirm'
		end
	end
	resources :diaries, only: [:index, :create, :update, :destroy] do
		member do
			get 'data'
		end
		collection do
			get 'record'
		end
	end
	resources :categories, only: [:index, :show]
	resources :inquiries, only: [:new, :create]

	namespace :admins do
		get 'home/top'
		resources :users, only: [:index]
		resources :foods, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :diaries, only: [:index, :show, :edit, :update, :destroy]
		resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :inquiries, only: [:index, :show, :destroy]
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :foods
	has_many :diary_categories
	has_many :diaries, through: :diary_categories
	has_one_attached :image

	validates :name, :image, :nutrition_type, :food_group, :caption, presence: true

	enum nutrition_type: {body:0, arrange:1, energy:2}
	enum food_group: {first_group:0, second_group:1, third_group:2, fourth_group:3, fifth_group:4, sixth_group:5}
end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :user
	has_one :event
	has_many :diary_categories
	has_many :categories, through: :diary_categories
	has_one_attached :b_image
	has_one_attached :l_image
	has_one_attached :d_image

	validates :user_id, :status, presence: true
	validates :categories, presence: true
	enum status: {active:0, closed:1}
end

app/models/diary_category.rb
class DiaryCategory < ApplicationRecord
	belongs_to :diary
	belongs_to :category
end

app/models/food.rb
class Food < ApplicationRecord
	belongs_to :category
	validates :name, :caption, :category_id,  presence: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
	validates :name, :email, :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: {maximum: 10, minimum: 2}
  validates :introduction, length: { maximum: 20 }

  has_many :diaries, dependent: :destroy

	enum status: {active:0, inactive:1}

	# 物理削除の代わりにユーザーの`deleted_at`をタイムスタンプで更新
  def soft_delete
    update_attribute(:deleted_at, Time.current)
    update_attributes(status: 1)
  end

  # ユーザーのアカウントが有効であることを確認
  def active_for_authentication?
    super && !deleted_at
  end

  # 削除したユーザーにカスタムメッセージを追加します
  def inactive_message
    !deleted_at ? super : :deleted_account
  end
end

app/controllers/admins/home_controller.rb
class Admins::HomeController < Admins::BaseController
	def top
		@users_count = User.count
		@diaries_count = Diary.count
		@categories_count = Category.count
		@foods_count = Food.count
		@inquiries_count = Inquiry.count
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show]

	# GET /categories
	# GET /categories.json
	def index
		@body_categories = Category.body
		@arange_categories = Category.arrange
		@energy_categories = Category.energy
	end

	# GET /categories/1
	# GET /categories/1.json
	def show
		@foods = @category.foods
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_category
			@category = Category.find(params[:id])
		end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_diary, only: [:show, :edit, :update, :destroy, :data]

	def index
		@diaries = current_user.diaries
		render 'index', formats: 'json', handlers: 'jbuilder'
	end

	def record
		@diary = current_user.diaries.find_or_initialize_by(date: params[:date])
		if @diary.new_record?
			render :new
		else
			render :edit
		end
	end


	# POST /diaries
	# POST /diaries.json
	def create
		@diary = current_user.diaries.new(diary_params)
		if @diary.save
			redirect_to current_user, notice: '登録が完了しました。'
		else
			redirect_back(fallback_location: root_path, alert: @diary.errors.full_messages.join(", "))
		end
	end

	# PATCH/PUT /diaries/1
	# PATCH/PUT /diaries/1.json
	def update
		if @diary.update(diary_params)
			redirect_to current_user, notice: '上書きが完了しました。' 
		else
			redirect_back(fallback_location: root_path, alert: @diary.errors.full_messages.join(", "))
		end
	end

	# DELETE /diaries/1
	# DELETE /diaries/1.json
	def destroy
		if @diary.destroy
			redirect_to current_user, notice: '削除しました。'
		else
			redirect_back(fallback_location: root_path, alert: @diary.errors.full_messages.join(", "))
		end
	end

	def data
		#選択した日から1週間前の摂取データを取得
		to  = @diary.date.at_end_of_day
		from = 6.days.ago(to).at_beginning_of_day
		#食品目ごとにデータを取得
		category_diaries_hash =
			current_user.diaries
				.where(date: from..to).map{|t|t.categories}
				.flatten.group_by(&:name)
				.map {|k, v| [k, v.size] }.to_h

		all_categories_hash = Category.all.map{ |c| [c.name, 0] }.to_h
		@records = all_categories_hash.merge(category_diaries_hash)
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_diary
			@diary = current_user.diaries.find(params[:id])
		end

		# Only allow a list of trusted parameters through.
		def diary_params
			params.require(:diary).permit(:user_id, :b_image, :l_image, :d_image, :date, :weight, :comment, category_ids: [])
		end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.fetch(:food, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

	# GET /inquiries/new
	def new
		@inquiry = Inquiry.new
	end

	# POST /inquiries
	# POST /inquiries.json
	def create
		@inquiry = Inquiry.new(inquiry_params)
		if @inquiry.save
			InquiryMailer.send_mail(@inquiry).deliver_now
			redirect_to root_path, notice: 'お問い合わせが送信されました。'
		else
			redirect_back(fallback_location: root_path, error: @inquiry.errors.full_messages.join(", "))
		end
	end


	private
		def inquiry_params
			params.require(:inquiry).permit(:name, :email, :message)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user, only: [:show, :edit]

	def show
	end

	def edit
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(@user), notice: 'ユーザー情報を更新しました。' 
		else
			redirect_back(fallback_location: root_path, error: @user.errors.full_messages.join(", "))
		end
	end

	def confirm
	end

	private

	def set_user
		@user = current_user
	end

	def user_params
		params.require(:user).permit(:name, :introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/diary_categories_helper.rb
module DiaryCategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/home/top.html.erb
<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

	<!-- Main Content -->
	<div id="content">

		<!-- Topbar -->
		<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

			<!-- Sidebar Toggle (Topbar) -->
			<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
				<i class="fa fa-bars"></i>
			</button>

			<!-- Topbar Search -->
			<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
				<div class="input-group">
					<input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
					<div class="input-group-append">
						<button class="btn btn-primary" type="button">
							<i class="fas fa-search fa-sm"></i>
						</button>
					</div>
				</div>
			</form>

			<!-- Topbar Navbar -->
			<ul class="navbar-nav ml-auto">

				<!-- Nav Item - Search Dropdown (Visible Only XS) -->
				<li class="nav-item dropdown no-arrow d-sm-none">
					<a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fas fa-search fa-fw"></i>
					</a>
					<!-- Dropdown - Messages -->
					<div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
						<form class="form-inline mr-auto w-100 navbar-search">
							<div class="input-group">
								<input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
								<div class="input-group-append">
									<button class="btn btn-primary" type="button">
										<i class="fas fa-search fa-sm"></i>
									</button>
								</div>
							</div>
						</form>
					</div>
				</li>
			</ul>

		</nav>
		<!-- End of Topbar -->

		<!-- Begin Page Content -->
		<div class="container-fluid">

			<!-- Content Row -->
			<div class="row">

				<!-- Earnings (Monthly) Card Example -->
				<div class="col-xl-3 col-md-6 mb-4">
					<div class="card border-left-primary shadow h-100 py-2">
						<div class="card-body">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Users</div>
									<div class="h5 mb-0 font-weight-bold text-gray-800"><%= @users_count %></div>
								</div>
								<div class="col-auto">
									<i class="fas fa-users fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Earnings (Monthly) Card Example -->
				<div class="col-xl-3 col-md-6 mb-4">
					<div class="card border-left-success shadow h-100 py-2">
						<div class="card-body">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="text-xs font-weight-bold text-success text-uppercase mb-1">Diaries</div>
									<div class="h5 mb-0 font-weight-bold text-gray-800"><%= @diaries_count %></div>
								</div>
								<div class="col-auto">
									<i class="far fa-calendar-alt fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Earnings (Monthly) Card Example -->
				<div class="col-xl-3 col-md-6 mb-4">
					<div class="card border-left-info shadow h-100 py-2">
						<div class="card-body">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="text-xs font-weight-bold text-info text-uppercase mb-1">Categories</div>
									<div class="row no-gutters align-items-center">
										<div class="col-auto">
											<div class="h5 mb-0 mr-3 font-weight-bold text-gray-800"><%= @categories_count %></div>
										</div>
									</div>
								</div>
								<div class="col-auto">
									<i class="far fa-object-group fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Pending Requests Card Example -->
				<div class="col-xl-3 col-md-6 mb-4">
					<div class="card border-left-warning shadow h-100 py-2">
						<div class="card-body">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Foods</div>
									<div class="h5 mb-0 font-weight-bold text-gray-800"><%= @foods_count %></div>
								</div>
								<div class="col-auto">
									<i class="fas fa-carrot fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-xl-3 col-md-6 mb-4">
					<div class="card border-left-warning shadow h-100 py-2">
						<div class="card-body">
							<div class="row no-gutters align-items-center">
								<div class="col mr-2">
									<div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Inquiries</div>
									<div class="h5 mb-0 font-weight-bold text-gray-800"><%= @inquiries_count %></div>
								</div>
								<div class="col-auto">
									<i class="far fa-envelope fa-2x text-gray-300"></i>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/about.html.slim
.container
	.row.mb-4
		.col-md-7.mb-4
			= image_tag "dish1.jpg", width: "100%"
		.col-md-5.p-md-4
			h6 健康な体を手に入れるためにはバランスの良い食事は不可欠です。
			h6 Meal Diaryでは６つの食品群からなる１２品目について記録することができます。
			h6 細かく記録していくことで、摂れている栄養と不足している栄養をしっかり把握することができます。
			h6 食事から健康へアプローチしていきましょう！
			br
			.text-center
				p 食品群・品目について詳しくはこちら
				.btn.page-link.text-dark.d-inline-block.mb-4(style="width:75%")
						= link_to 'Click！', categories_path

	.row.mb-2
		.col-md-12
			h5 Meal Diaryでできること
	.row.mb-4
		.col-md-4.mb-4
			= image_tag "obj1.jpg", width: "95%", class: "mb-2"
			h5 1. 食事を記録
			.p-1
				h6 日々の食事でどの栄養が取れているのか、どの栄養が足りていないのか。
				h6 日記形式で可視化して記録することで栄養バランスをわかりやすく管理できます。
		.col-md-4.mb-4
			= image_tag "obj2.jpg", width: "95%", class: "mb-2"
			h5 2. 献立を考えるお手伝い
			.p-1
				h6 Meal Diaryでは朝昼晩の３食を写真で残すことができます。
				h6 いつ何を食べたか簡単に確認できるので、写真を見返すことで毎日の献立を考える際に役立ちます。
		.col-md-4.mb-4
			= image_tag "obj3.jpg", width: "95%", class: "mb-2"
			h5 3. 体質改善もサポート
			.p-1
				h6 不健康な身体の原因は食事であることが多いです。
				h6 食事の記録と一緒に体重管理もできるので、食事の内容と体重変動の因果関係を突き止め、健康意識を高めましょう！


	.row.mb-4
		.col-md-6
			.text-center
				h6.mb-2  Meal Diaryを使ってみる
				.btn-horizontal-border.mb-4(style="width:50%")
					= link_to "Sign Up", new_user_registration_path
		.col-md-6
			.text-center
				h6.mb-2  Meal Diaryの使い方
				.btn-horizontal-border.mb-4(style="width:50%")
					= link_to "How to", home_howto_path

	

app/views/home/howto.html.slim
.container
	.row.mb-4
		.col-md-8.offset-md-2.my-auto
			h4.font-weight-bold Meal Diaryの使い方
	.row.mb-4
		.col-md-2
		.col-md-4
			h5.font-weight-bold.bg-light.my-md-4 １．マイページへ
			.p-md-5
				p カレンダーから食事記録をしたい日を選択する
				p ※ 当日以外も選択可能
		.col-md-4.my-md-4
			= image_tag "howto1.jpg", width: "95%"
	.row.mb-4
		.col-md-2
		.col-md-4
			h5.font-weight-bold.bg-light.my-md-4 ２．食品目を選択　　※入力必須
			.p-md-5
				p 12食品目から摂取した食品目にチェックを入れる
		.col-md-4.my-md-4
			= image_tag "howto2.jpg", width: "95%"
	.row.mb-4
		.col-md-2
		.col-md-4
			h5.font-weight-bold.bg-light.my-md-4 ３．食事画像、体重、MEMOの登録
			.p-md-5
				p それぞれ必要に応じて登録
				p こちらの３項目については任意のため登録しなくてもOK！
				br
				p 《記録》をクリックすれば完了
		.col-md-4.my-md-4
			= image_tag "howto3.jpg", width: "95%"

app/views/home/top.html.slim
.container.welcome-section
	.row
		.col-md-10.offset-md-1.my-auto
			.top-slider
				.slider
					= image_tag "top1.jpg", class: "top-image"
				.slider
					= image_tag "top2.jpg", class: "top-image"
				.slider
					= image_tag "top3.jpg", class: "top-image"
				.slider
					= image_tag "top4.jpg", class: "top-image"
			br
			br
	.row.mb-4
		.col-md-4
			.text-center
				h6 Meal Diaryについて詳しく見る
				.btn-horizontal-border.mb-4(style="width:80%")
					= link_to "About", home_about_path
		.col-md-4
			.text-center
				h6  Meal Diaryを使ってみる
				.btn-horizontal-border.mb-4(style="width:80%")
					= link_to "Sign Up", new_user_registration_path
		.col-md-4
			.text-center
				h6.mb-2  Meal Diaryの使い方
				.btn-horizontal-border.mb-4(style="width:80%")
					= link_to "How to", home_howto_path